version: '3.8'

services:
  # BROKER CENTRAL
  broker:
    build:
      context: ./Broker_C1
      dockerfile: Dockerfile
    container_name: cyberday_broker
    ports:
      - "50051:50051"
    networks:
      - cyberday_network
    volumes:
      - ./shared:/shared
    environment:
      - TZ=America/Santiago
    depends_on:
      - db1
      - db2
      - db3

  # NODOS DE BASE DE DATOS
  db1:
    build:
      context: ./Riploy_BD1_C2
      dockerfile: BD1/Dockerfile
    container_name: cyberday_db1
    ports:
      - "50052:50052"
    networks:
      - cyberday_network
    volumes:
      - db1_data:/data
    environment:
      - NODO_ID=DB1
      - PUERTO=:50052
      - TZ=America/Santiago

  db2:
    build:
      context: ./Falabellox_BD2_C3
      dockerfile: BD2/Dockerfile
    container_name: cyberday_db2
    ports:
      - "50053:50053"
    networks:
      - cyberday_network
    volumes:
      - db2_data:/data
    environment:
      - NODO_ID=DB2
      - PUERTO=:50053
      - TZ=America/Santiago

  db3:
    build:
      context: ./Parisio_BD3
      dockerfile: BD3/Dockerfile
    container_name: cyberday_db3
    ports:
      - "50054:50054"
    networks:
      - cyberday_network
    volumes:
      - db3_data:/data
    environment:
      - NODO_ID=DB3
      - PUERTO=:50054
      - TZ=America/Santiago

  # PRODUCTORES
  riploy:
    build:
      context: ./Riploy_BD1_C2
      dockerfile: Riploy/Dockerfile
    container_name: cyberday_riploy
    networks:
      - cyberday_network
    environment:
      - PRODUCTOR_NOMBRE=Riploy
      - CATALOGO=riploy_catalogo.csv
      - TZ=America/Santiago
    depends_on:
      - broker

  falabellox:
    build:
      context: ./Falabellox_BD2_C3
      dockerfile: Falabellox/Dockerfile
    container_name: cyberday_falabellox
    networks:
      - cyberday_network
    environment:
      - PRODUCTOR_NOMBRE=Falabellox
      - CATALOGO=falabellox_catalogo.csv
      - TZ=America/Santiago
    depends_on:
      - broker

  parisio:
    build:
      context: ./Parisio_BD3
      dockerfile: Parisio/Dockerfile
    container_name: cyberday_parisio
    networks:
      - cyberday_network
    environment:
      - PRODUCTOR_NOMBRE=Parisio
      - CATALOGO=parisio_catalogo.csv
      - TZ=America/Santiago
    depends_on:
      - broker

  # CONSUMIDORES GRUPO 1 (C1)
  consumidor_c1_1:
    build:
      context: ./Consumidores
      dockerfile: Dockerfile
    container_name: cyberday_consumidor_c1_1
    networks:
      - cyberday_network
    ports:
      - "50061:50061"
    volumes:
      - consumidor_c1_1_data:/data
      - ./consumidores.csv:/app/consumidores.csv:ro
    environment:
      - CONSUMIDOR_ID=C1-1
      - BROKER_ADDR=broker:50051
      - TZ=America/Santiago
    depends_on:
      - broker

  consumidor_c1_2:
    build:
      context: ./Consumidores
      dockerfile: Dockerfile
    container_name: cyberday_consumidor_c1_2
    networks:
      - cyberday_network
    ports:
      - "50062:50062"
    volumes:
      - consumidor_c1_2_data:/data
      - ./consumidores.csv:/app/consumidores.csv:ro
    environment:
      - CONSUMIDOR_ID=C1-2
      - BROKER_ADDR=broker:50051
      - TZ=America/Santiago
    depends_on:
      - broker

  consumidor_c1_3:
    build:
      context: ./Consumidores
      dockerfile: Dockerfile
    container_name: cyberday_consumidor_c1_3
    networks:
      - cyberday_network
    ports:
      - "50063:50063"
    volumes:
      - consumidor_c1_3_data:/data
      - ./consumidores.csv:/app/consumidores.csv:ro
    environment:
      - CONSUMIDOR_ID=C1-3
      - BROKER_ADDR=broker:50051
      - TZ=America/Santiago
    depends_on:
      - broker

  consumidor_c1_4:
    build:
      context: ./Consumidores
      dockerfile: Dockerfile
    container_name: cyberday_consumidor_c1_4
    networks:
      - cyberday_network
    ports:
      - "50064:50064"
    volumes:
      - consumidor_c1_4_data:/data
      - ./consumidores.csv:/app/consumidores.csv:ro
    environment:
      - CONSUMIDOR_ID=C1-4
      - BROKER_ADDR=broker:50051
      - TZ=America/Santiago
    depends_on:
      - broker

  # CONSUMIDORES GRUPO 2 (C2)
  consumidor_c2_1:
    build:
      context: ./Consumidores
      dockerfile: Dockerfile
    container_name: cyberday_consumidor_c2_1
    networks:
      - cyberday_network
    ports:
      - "50065:50065"
    volumes:
      - consumidor_c2_1_data:/data
      - ./consumidores.csv:/app/consumidores.csv:ro
    environment:
      - CONSUMIDOR_ID=C2-1
      - BROKER_ADDR=broker:50051
      - TZ=America/Santiago
    depends_on:
      - broker

  consumidor_c2_2:
    build:
      context: ./Consumidores
      dockerfile: Dockerfile
    container_name: cyberday_consumidor_c2_2
    networks:
      - cyberday_network
    ports:
      - "50066:50066"
    volumes:
      - consumidor_c2_2_data:/data
      - ./consumidores.csv:/app/consumidores.csv:ro
    environment:
      - CONSUMIDOR_ID=C2-2
      - BROKER_ADDR=broker:50051
      - TZ=America/Santiago
    depends_on:
      - broker

  consumidor_c2_3:
    build:
      context: ./Consumidores
      dockerfile: Dockerfile
    container_name: cyberday_consumidor_c2_3
    networks:
      - cyberday_network
    ports:
      - "50067:50067"
    volumes:
      - consumidor_c2_3_data:/data
      - ./consumidores.csv:/app/consumidores.csv:ro
    environment:
      - CONSUMIDOR_ID=C2-3
      - BROKER_ADDR=broker:50051
      - TZ=America/Santiago
    depends_on:
      - broker

  consumidor_c2_4:
    build:
      context: ./Consumidores
      dockerfile: Dockerfile
    container_name: cyberday_consumidor_c2_4
    networks:
      - cyberday_network
    ports:
      - "50068:50068"
    volumes:
      - consumidor_c2_4_data:/data
      - ./consumidores.csv:/app/consumidores.csv:ro
    environment:
      - CONSUMIDOR_ID=C2-4
      - BROKER_ADDR=broker:50051
      - TZ=America/Santiago
    depends_on:
      - broker

  # CONSUMIDORES GRUPO 3 (C3)
  consumidor_c3_1:
    build:
      context: ./Consumidores
      dockerfile: Dockerfile
    container_name: cyberday_consumidor_c3_1
    networks:
      - cyberday_network
    ports:
      - "50069:50069"
    volumes:
      - consumidor_c3_1_data:/data
      - ./consumidores.csv:/app/consumidores.csv:ro
    environment:
      - CONSUMIDOR_ID=C3-1
      - BROKER_ADDR=broker:50051
      - TZ=America/Santiago
    depends_on:
      - broker

  consumidor_c3_2:
    build:
      context: ./Consumidores
      dockerfile: Dockerfile
    container_name: cyberday_consumidor_c3_2
    networks:
      - cyberday_network
    ports:
      - "50070:50070"
    volumes:
      - consumidor_c3_2_data:/data
      - ./consumidores.csv:/app/consumidores.csv:ro
    environment:
      - CONSUMIDOR_ID=C3-2
      - BROKER_ADDR=broker:50051
      - TZ=America/Santiago
    depends_on:
      - broker

  consumidor_c3_3:
    build:
      context: ./Consumidores
      dockerfile: Dockerfile
    container_name: cyberday_consumidor_c3_3
    networks:
      - cyberday_network
    ports:
      - "50071:50071"
    volumes:
      - consumidor_c3_3_data:/data
      - ./consumidores.csv:/app/consumidores.csv:ro
    environment:
      - CONSUMIDOR_ID=C3-3
      - BROKER_ADDR=broker:50051
      - TZ=America/Santiago
    depends_on:
      - broker

  consumidor_c3_4:
    build:
      context: ./Consumidores
      dockerfile: Dockerfile
    container_name: cyberday_consumidor_c3_4
    networks:
      - cyberday_network
    ports:
      - "50072:50072"
    volumes:
      - consumidor_c3_4_data:/data
      - ./consumidores.csv:/app/consumidores.csv:ro
    environment:
      - CONSUMIDOR_ID=C3-4
      - BROKER_ADDR=broker:50051
      - TZ=America/Santiago
    depends_on:
      - broker

networks:
  cyberday_network:
    driver: bridge

volumes:
  db1_data:
  db2_data:
  db3_data:
  consumidor_c1_1_data:
  consumidor_c1_2_data:
  consumidor_c1_3_data:
  consumidor_c1_4_data:
  consumidor_c2_1_data:
  consumidor_c2_2_data:
  consumidor_c2_3_data:
  consumidor_c2_4_data:
  consumidor_c3_1_data:
  consumidor_c3_2_data:
  consumidor_c3_3_data:
  consumidor_c3_4_data:
