// Especifica la versión de la sintaxis de Protocol Buffers.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/ofertas.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OfertasRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProductoId      string                 `protobuf:"bytes,1,opt,name=producto_id,json=productoId,proto3" json:"producto_id,omitempty"`
	Tienda          string                 `protobuf:"bytes,2,opt,name=tienda,proto3" json:"tienda,omitempty"`
	Categoria       string                 `protobuf:"bytes,3,opt,name=categoria,proto3" json:"categoria,omitempty"`
	Producto        string                 `protobuf:"bytes,4,opt,name=producto,proto3" json:"producto,omitempty"`
	PrecioDescuento int32                  `protobuf:"varint,5,opt,name=precio_descuento,json=precioDescuento,proto3" json:"precio_descuento,omitempty"`
	Stock           int32                  `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	Fecha           string                 `protobuf:"bytes,7,opt,name=fecha,proto3" json:"fecha,omitempty"`
	ClienteId       string                 `protobuf:"bytes,8,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OfertasRequest) Reset() {
	*x = OfertasRequest{}
	mi := &file_proto_ofertas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfertasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfertasRequest) ProtoMessage() {}

func (x *OfertasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ofertas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfertasRequest.ProtoReflect.Descriptor instead.
func (*OfertasRequest) Descriptor() ([]byte, []int) {
	return file_proto_ofertas_proto_rawDescGZIP(), []int{0}
}

func (x *OfertasRequest) GetProductoId() string {
	if x != nil {
		return x.ProductoId
	}
	return ""
}

func (x *OfertasRequest) GetTienda() string {
	if x != nil {
		return x.Tienda
	}
	return ""
}

func (x *OfertasRequest) GetCategoria() string {
	if x != nil {
		return x.Categoria
	}
	return ""
}

func (x *OfertasRequest) GetProducto() string {
	if x != nil {
		return x.Producto
	}
	return ""
}

func (x *OfertasRequest) GetPrecioDescuento() int32 {
	if x != nil {
		return x.PrecioDescuento
	}
	return 0
}

func (x *OfertasRequest) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *OfertasRequest) GetFecha() string {
	if x != nil {
		return x.Fecha
	}
	return ""
}

func (x *OfertasRequest) GetClienteId() string {
	if x != nil {
		return x.ClienteId
	}
	return ""
}

type OfertasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrokerMessage string                 `protobuf:"bytes,1,opt,name=broker_message,json=brokerMessage,proto3" json:"broker_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfertasResponse) Reset() {
	*x = OfertasResponse{}
	mi := &file_proto_ofertas_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfertasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfertasResponse) ProtoMessage() {}

func (x *OfertasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ofertas_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfertasResponse.ProtoReflect.Descriptor instead.
func (*OfertasResponse) Descriptor() ([]byte, []int) {
	return file_proto_ofertas_proto_rawDescGZIP(), []int{1}
}

func (x *OfertasResponse) GetBrokerMessage() string {
	if x != nil {
		return x.BrokerMessage
	}
	return ""
}

var File_proto_ofertas_proto protoreflect.FileDescriptor

const file_proto_ofertas_proto_rawDesc = "" +
	"\n" +
	"\x13proto/ofertas.proto\"\xf9\x01\n" +
	"\x0eOfertasRequest\x12\x1f\n" +
	"\vproducto_id\x18\x01 \x01(\tR\n" +
	"productoId\x12\x16\n" +
	"\x06tienda\x18\x02 \x01(\tR\x06tienda\x12\x1c\n" +
	"\tcategoria\x18\x03 \x01(\tR\tcategoria\x12\x1a\n" +
	"\bproducto\x18\x04 \x01(\tR\bproducto\x12)\n" +
	"\x10precio_descuento\x18\x05 \x01(\x05R\x0fprecioDescuento\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x05R\x05stock\x12\x14\n" +
	"\x05fecha\x18\a \x01(\tR\x05fecha\x12\x1d\n" +
	"\n" +
	"cliente_id\x18\b \x01(\tR\tclienteId\"8\n" +
	"\x0fOfertasResponse\x12%\n" +
	"\x0ebroker_message\x18\x01 \x01(\tR\rbrokerMessage27\n" +
	"\aOfertas\x12,\n" +
	"\aOfertas\x12\x0f.OfertasRequest\x1a\x10.OfertasResponseB\bZ\x06/protob\x06proto3"

var (
	file_proto_ofertas_proto_rawDescOnce sync.Once
	file_proto_ofertas_proto_rawDescData []byte
)

func file_proto_ofertas_proto_rawDescGZIP() []byte {
	file_proto_ofertas_proto_rawDescOnce.Do(func() {
		file_proto_ofertas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ofertas_proto_rawDesc), len(file_proto_ofertas_proto_rawDesc)))
	})
	return file_proto_ofertas_proto_rawDescData
}

var file_proto_ofertas_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ofertas_proto_goTypes = []any{
	(*OfertasRequest)(nil),  // 0: OfertasRequest
	(*OfertasResponse)(nil), // 1: OfertasResponse
}
var file_proto_ofertas_proto_depIdxs = []int32{
	0, // 0: Ofertas.Ofertas:input_type -> OfertasRequest
	1, // 1: Ofertas.Ofertas:output_type -> OfertasResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ofertas_proto_init() }
func file_proto_ofertas_proto_init() {
	if File_proto_ofertas_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ofertas_proto_rawDesc), len(file_proto_ofertas_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ofertas_proto_goTypes,
		DependencyIndexes: file_proto_ofertas_proto_depIdxs,
		MessageInfos:      file_proto_ofertas_proto_msgTypes,
	}.Build()
	File_proto_ofertas_proto = out.File
	file_proto_ofertas_proto_goTypes = nil
	file_proto_ofertas_proto_depIdxs = nil
}
