// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.26.1
// source: proto/ofertas.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mensajes
type OfertaRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OfertaId        string                 `protobuf:"bytes,1,opt,name=oferta_id,json=ofertaId,proto3" json:"oferta_id,omitempty"`
	ProductoId      string                 `protobuf:"bytes,2,opt,name=producto_id,json=productoId,proto3" json:"producto_id,omitempty"`
	Tienda          string                 `protobuf:"bytes,3,opt,name=tienda,proto3" json:"tienda,omitempty"`
	Categoria       string                 `protobuf:"bytes,4,opt,name=categoria,proto3" json:"categoria,omitempty"`
	Producto        string                 `protobuf:"bytes,5,opt,name=producto,proto3" json:"producto,omitempty"`
	PrecioDescuento int32                  `protobuf:"varint,6,opt,name=precio_descuento,json=precioDescuento,proto3" json:"precio_descuento,omitempty"`
	Stock           int32                  `protobuf:"varint,7,opt,name=stock,proto3" json:"stock,omitempty"`
	Fecha           string                 `protobuf:"bytes,8,opt,name=fecha,proto3" json:"fecha,omitempty"`
	ClienteId       string                 `protobuf:"bytes,9,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
	Timestamp       int64                  `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OfertaRequest) Reset() {
	*x = OfertaRequest{}
	mi := &file_proto_ofertas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfertaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfertaRequest) ProtoMessage() {}

func (x *OfertaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ofertas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfertaRequest.ProtoReflect.Descriptor instead.
func (*OfertaRequest) Descriptor() ([]byte, []int) {
	return file_proto_ofertas_proto_rawDescGZIP(), []int{0}
}

func (x *OfertaRequest) GetOfertaId() string {
	if x != nil {
		return x.OfertaId
	}
	return ""
}

func (x *OfertaRequest) GetProductoId() string {
	if x != nil {
		return x.ProductoId
	}
	return ""
}

func (x *OfertaRequest) GetTienda() string {
	if x != nil {
		return x.Tienda
	}
	return ""
}

func (x *OfertaRequest) GetCategoria() string {
	if x != nil {
		return x.Categoria
	}
	return ""
}

func (x *OfertaRequest) GetProducto() string {
	if x != nil {
		return x.Producto
	}
	return ""
}

func (x *OfertaRequest) GetPrecioDescuento() int32 {
	if x != nil {
		return x.PrecioDescuento
	}
	return 0
}

func (x *OfertaRequest) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *OfertaRequest) GetFecha() string {
	if x != nil {
		return x.Fecha
	}
	return ""
}

func (x *OfertaRequest) GetClienteId() string {
	if x != nil {
		return x.ClienteId
	}
	return ""
}

func (x *OfertaRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type OfertaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfertaResponse) Reset() {
	*x = OfertaResponse{}
	mi := &file_proto_ofertas_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfertaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfertaResponse) ProtoMessage() {}

func (x *OfertaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ofertas_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfertaResponse.ProtoReflect.Descriptor instead.
func (*OfertaResponse) Descriptor() ([]byte, []int) {
	return file_proto_ofertas_proto_rawDescGZIP(), []int{1}
}

func (x *OfertaResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *OfertaResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type AckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	NodoId        string                 `protobuf:"bytes,2,opt,name=nodo_id,json=nodoId,proto3" json:"nodo_id,omitempty"`
	Mensaje       string                 `protobuf:"bytes,3,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_proto_ofertas_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ofertas_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_proto_ofertas_proto_rawDescGZIP(), []int{2}
}

func (x *AckResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *AckResponse) GetNodoId() string {
	if x != nil {
		return x.NodoId
	}
	return ""
}

func (x *AckResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type RegistroConsumidorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumidorId  string                 `protobuf:"bytes,1,opt,name=consumidor_id,json=consumidorId,proto3" json:"consumidor_id,omitempty"`
	Categorias    []string               `protobuf:"bytes,2,rep,name=categorias,proto3" json:"categorias,omitempty"`
	Tiendas       []string               `protobuf:"bytes,3,rep,name=tiendas,proto3" json:"tiendas,omitempty"`
	PrecioMax     int32                  `protobuf:"varint,4,opt,name=precio_max,json=precioMax,proto3" json:"precio_max,omitempty"`
	DireccionGrpc string                 `protobuf:"bytes,5,opt,name=direccion_grpc,json=direccionGrpc,proto3" json:"direccion_grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistroConsumidorRequest) Reset() {
	*x = RegistroConsumidorRequest{}
	mi := &file_proto_ofertas_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistroConsumidorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistroConsumidorRequest) ProtoMessage() {}

func (x *RegistroConsumidorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ofertas_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistroConsumidorRequest.ProtoReflect.Descriptor instead.
func (*RegistroConsumidorRequest) Descriptor() ([]byte, []int) {
	return file_proto_ofertas_proto_rawDescGZIP(), []int{3}
}

func (x *RegistroConsumidorRequest) GetConsumidorId() string {
	if x != nil {
		return x.ConsumidorId
	}
	return ""
}

func (x *RegistroConsumidorRequest) GetCategorias() []string {
	if x != nil {
		return x.Categorias
	}
	return nil
}

func (x *RegistroConsumidorRequest) GetTiendas() []string {
	if x != nil {
		return x.Tiendas
	}
	return nil
}

func (x *RegistroConsumidorRequest) GetPrecioMax() int32 {
	if x != nil {
		return x.PrecioMax
	}
	return 0
}

func (x *RegistroConsumidorRequest) GetDireccionGrpc() string {
	if x != nil {
		return x.DireccionGrpc
	}
	return ""
}

type RegistroConsumidorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistroConsumidorResponse) Reset() {
	*x = RegistroConsumidorResponse{}
	mi := &file_proto_ofertas_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistroConsumidorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistroConsumidorResponse) ProtoMessage() {}

func (x *RegistroConsumidorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ofertas_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistroConsumidorResponse.ProtoReflect.Descriptor instead.
func (*RegistroConsumidorResponse) Descriptor() ([]byte, []int) {
	return file_proto_ofertas_proto_rawDescGZIP(), []int{4}
}

func (x *RegistroConsumidorResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *RegistroConsumidorResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type SolicitarHistoricoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumidorId  string                 `protobuf:"bytes,1,opt,name=consumidor_id,json=consumidorId,proto3" json:"consumidor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolicitarHistoricoRequest) Reset() {
	*x = SolicitarHistoricoRequest{}
	mi := &file_proto_ofertas_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolicitarHistoricoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitarHistoricoRequest) ProtoMessage() {}

func (x *SolicitarHistoricoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ofertas_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitarHistoricoRequest.ProtoReflect.Descriptor instead.
func (*SolicitarHistoricoRequest) Descriptor() ([]byte, []int) {
	return file_proto_ofertas_proto_rawDescGZIP(), []int{5}
}

func (x *SolicitarHistoricoRequest) GetConsumidorId() string {
	if x != nil {
		return x.ConsumidorId
	}
	return ""
}

type HistoricoConsumidorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ofertas       []*OfertaRequest       `protobuf:"bytes,1,rep,name=ofertas,proto3" json:"ofertas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoricoConsumidorResponse) Reset() {
	*x = HistoricoConsumidorResponse{}
	mi := &file_proto_ofertas_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoricoConsumidorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoricoConsumidorResponse) ProtoMessage() {}

func (x *HistoricoConsumidorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ofertas_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoricoConsumidorResponse.ProtoReflect.Descriptor instead.
func (*HistoricoConsumidorResponse) Descriptor() ([]byte, []int) {
	return file_proto_ofertas_proto_rawDescGZIP(), []int{6}
}

func (x *HistoricoConsumidorResponse) GetOfertas() []*OfertaRequest {
	if x != nil {
		return x.Ofertas
	}
	return nil
}

type LeerHistoricoRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodoId         string                 `protobuf:"bytes,1,opt,name=nodo_id,json=nodoId,proto3" json:"nodo_id,omitempty"`
	DesdeTimestamp int64                  `protobuf:"varint,2,opt,name=desde_timestamp,json=desdeTimestamp,proto3" json:"desde_timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LeerHistoricoRequest) Reset() {
	*x = LeerHistoricoRequest{}
	mi := &file_proto_ofertas_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeerHistoricoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeerHistoricoRequest) ProtoMessage() {}

func (x *LeerHistoricoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ofertas_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeerHistoricoRequest.ProtoReflect.Descriptor instead.
func (*LeerHistoricoRequest) Descriptor() ([]byte, []int) {
	return file_proto_ofertas_proto_rawDescGZIP(), []int{7}
}

func (x *LeerHistoricoRequest) GetNodoId() string {
	if x != nil {
		return x.NodoId
	}
	return ""
}

func (x *LeerHistoricoRequest) GetDesdeTimestamp() int64 {
	if x != nil {
		return x.DesdeTimestamp
	}
	return 0
}

type HistoricoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ofertas       []*OfertaRequest       `protobuf:"bytes,1,rep,name=ofertas,proto3" json:"ofertas,omitempty"`
	NodoId        string                 `protobuf:"bytes,2,opt,name=nodo_id,json=nodoId,proto3" json:"nodo_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoricoResponse) Reset() {
	*x = HistoricoResponse{}
	mi := &file_proto_ofertas_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoricoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoricoResponse) ProtoMessage() {}

func (x *HistoricoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ofertas_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoricoResponse.ProtoReflect.Descriptor instead.
func (*HistoricoResponse) Descriptor() ([]byte, []int) {
	return file_proto_ofertas_proto_rawDescGZIP(), []int{8}
}

func (x *HistoricoResponse) GetOfertas() []*OfertaRequest {
	if x != nil {
		return x.Ofertas
	}
	return nil
}

func (x *HistoricoResponse) GetNodoId() string {
	if x != nil {
		return x.NodoId
	}
	return ""
}

type SincronizarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodoOrigen    string                 `protobuf:"bytes,1,opt,name=nodo_origen,json=nodoOrigen,proto3" json:"nodo_origen,omitempty"`
	Ofertas       []*OfertaRequest       `protobuf:"bytes,2,rep,name=ofertas,proto3" json:"ofertas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SincronizarRequest) Reset() {
	*x = SincronizarRequest{}
	mi := &file_proto_ofertas_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SincronizarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SincronizarRequest) ProtoMessage() {}

func (x *SincronizarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ofertas_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SincronizarRequest.ProtoReflect.Descriptor instead.
func (*SincronizarRequest) Descriptor() ([]byte, []int) {
	return file_proto_ofertas_proto_rawDescGZIP(), []int{9}
}

func (x *SincronizarRequest) GetNodoOrigen() string {
	if x != nil {
		return x.NodoOrigen
	}
	return ""
}

func (x *SincronizarRequest) GetOfertas() []*OfertaRequest {
	if x != nil {
		return x.Ofertas
	}
	return nil
}

type SincronizarResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Exito                bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	OfertasSincronizadas int32                  `protobuf:"varint,2,opt,name=ofertas_sincronizadas,json=ofertasSincronizadas,proto3" json:"ofertas_sincronizadas,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SincronizarResponse) Reset() {
	*x = SincronizarResponse{}
	mi := &file_proto_ofertas_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SincronizarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SincronizarResponse) ProtoMessage() {}

func (x *SincronizarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ofertas_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SincronizarResponse.ProtoReflect.Descriptor instead.
func (*SincronizarResponse) Descriptor() ([]byte, []int) {
	return file_proto_ofertas_proto_rawDescGZIP(), []int{10}
}

func (x *SincronizarResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *SincronizarResponse) GetOfertasSincronizadas() int32 {
	if x != nil {
		return x.OfertasSincronizadas
	}
	return 0
}

var File_proto_ofertas_proto protoreflect.FileDescriptor

const file_proto_ofertas_proto_rawDesc = "" +
	"\n" +
	"\x13proto/ofertas.proto\"\xb3\x02\n" +
	"\rOfertaRequest\x12\x1b\n" +
	"\toferta_id\x18\x01 \x01(\tR\bofertaId\x12\x1f\n" +
	"\vproducto_id\x18\x02 \x01(\tR\n" +
	"productoId\x12\x16\n" +
	"\x06tienda\x18\x03 \x01(\tR\x06tienda\x12\x1c\n" +
	"\tcategoria\x18\x04 \x01(\tR\tcategoria\x12\x1a\n" +
	"\bproducto\x18\x05 \x01(\tR\bproducto\x12)\n" +
	"\x10precio_descuento\x18\x06 \x01(\x05R\x0fprecioDescuento\x12\x14\n" +
	"\x05stock\x18\a \x01(\x05R\x05stock\x12\x14\n" +
	"\x05fecha\x18\b \x01(\tR\x05fecha\x12\x1d\n" +
	"\n" +
	"cliente_id\x18\t \x01(\tR\tclienteId\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\x03R\ttimestamp\"@\n" +
	"\x0eOfertaResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\"V\n" +
	"\vAckResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x17\n" +
	"\anodo_id\x18\x02 \x01(\tR\x06nodoId\x12\x18\n" +
	"\amensaje\x18\x03 \x01(\tR\amensaje\"\xc0\x01\n" +
	"\x19RegistroConsumidorRequest\x12#\n" +
	"\rconsumidor_id\x18\x01 \x01(\tR\fconsumidorId\x12\x1e\n" +
	"\n" +
	"categorias\x18\x02 \x03(\tR\n" +
	"categorias\x12\x18\n" +
	"\atiendas\x18\x03 \x03(\tR\atiendas\x12\x1d\n" +
	"\n" +
	"precio_max\x18\x04 \x01(\x05R\tprecioMax\x12%\n" +
	"\x0edireccion_grpc\x18\x05 \x01(\tR\rdireccionGrpc\"L\n" +
	"\x1aRegistroConsumidorResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\"@\n" +
	"\x19SolicitarHistoricoRequest\x12#\n" +
	"\rconsumidor_id\x18\x01 \x01(\tR\fconsumidorId\"G\n" +
	"\x1bHistoricoConsumidorResponse\x12(\n" +
	"\aofertas\x18\x01 \x03(\v2\x0e.OfertaRequestR\aofertas\"X\n" +
	"\x14LeerHistoricoRequest\x12\x17\n" +
	"\anodo_id\x18\x01 \x01(\tR\x06nodoId\x12'\n" +
	"\x0fdesde_timestamp\x18\x02 \x01(\x03R\x0edesdeTimestamp\"V\n" +
	"\x11HistoricoResponse\x12(\n" +
	"\aofertas\x18\x01 \x03(\v2\x0e.OfertaRequestR\aofertas\x12\x17\n" +
	"\anodo_id\x18\x02 \x01(\tR\x06nodoId\"_\n" +
	"\x12SincronizarRequest\x12\x1f\n" +
	"\vnodo_origen\x18\x01 \x01(\tR\n" +
	"nodoOrigen\x12(\n" +
	"\aofertas\x18\x02 \x03(\v2\x0e.OfertaRequestR\aofertas\"`\n" +
	"\x13SincronizarResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x123\n" +
	"\x15ofertas_sincronizadas\x18\x02 \x01(\x05R\x14ofertasSincronizadas2:\n" +
	"\aOfertas\x12/\n" +
	"\fEnviarOferta\x12\x0e.OfertaRequest\x1a\x0f.OfertaResponse2\xaf\x01\n" +
	"\bDynamoDB\x12-\n" +
	"\rGuardarOferta\x12\x0e.OfertaRequest\x1a\f.AckResponse\x12:\n" +
	"\rLeerHistorico\x12\x15.LeerHistoricoRequest\x1a\x12.HistoricoResponse\x128\n" +
	"\vSincronizar\x12\x13.SincronizarRequest\x1a\x14.SincronizarResponse2\xac\x01\n" +
	"\n" +
	"Consumidor\x12N\n" +
	"\x13RegistrarConsumidor\x12\x1a.RegistroConsumidorRequest\x1a\x1b.RegistroConsumidorResponse\x12N\n" +
	"\x12SolicitarHistorico\x12\x1a.SolicitarHistoricoRequest\x1a\x1c.HistoricoConsumidorResponse2I\n" +
	"\x18NotificacionesConsumidor\x12-\n" +
	"\rRecibirOferta\x12\x0e.OfertaRequest\x1a\f.AckResponseB\bZ\x06/protob\x06proto3"

var (
	file_proto_ofertas_proto_rawDescOnce sync.Once
	file_proto_ofertas_proto_rawDescData []byte
)

func file_proto_ofertas_proto_rawDescGZIP() []byte {
	file_proto_ofertas_proto_rawDescOnce.Do(func() {
		file_proto_ofertas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ofertas_proto_rawDesc), len(file_proto_ofertas_proto_rawDesc)))
	})
	return file_proto_ofertas_proto_rawDescData
}

var file_proto_ofertas_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_ofertas_proto_goTypes = []any{
	(*OfertaRequest)(nil),               // 0: OfertaRequest
	(*OfertaResponse)(nil),              // 1: OfertaResponse
	(*AckResponse)(nil),                 // 2: AckResponse
	(*RegistroConsumidorRequest)(nil),   // 3: RegistroConsumidorRequest
	(*RegistroConsumidorResponse)(nil),  // 4: RegistroConsumidorResponse
	(*SolicitarHistoricoRequest)(nil),   // 5: SolicitarHistoricoRequest
	(*HistoricoConsumidorResponse)(nil), // 6: HistoricoConsumidorResponse
	(*LeerHistoricoRequest)(nil),        // 7: LeerHistoricoRequest
	(*HistoricoResponse)(nil),           // 8: HistoricoResponse
	(*SincronizarRequest)(nil),          // 9: SincronizarRequest
	(*SincronizarResponse)(nil),         // 10: SincronizarResponse
}
var file_proto_ofertas_proto_depIdxs = []int32{
	0,  // 0: HistoricoConsumidorResponse.ofertas:type_name -> OfertaRequest
	0,  // 1: HistoricoResponse.ofertas:type_name -> OfertaRequest
	0,  // 2: SincronizarRequest.ofertas:type_name -> OfertaRequest
	0,  // 3: Ofertas.EnviarOferta:input_type -> OfertaRequest
	0,  // 4: DynamoDB.GuardarOferta:input_type -> OfertaRequest
	7,  // 5: DynamoDB.LeerHistorico:input_type -> LeerHistoricoRequest
	9,  // 6: DynamoDB.Sincronizar:input_type -> SincronizarRequest
	3,  // 7: Consumidor.RegistrarConsumidor:input_type -> RegistroConsumidorRequest
	5,  // 8: Consumidor.SolicitarHistorico:input_type -> SolicitarHistoricoRequest
	0,  // 9: NotificacionesConsumidor.RecibirOferta:input_type -> OfertaRequest
	1,  // 10: Ofertas.EnviarOferta:output_type -> OfertaResponse
	2,  // 11: DynamoDB.GuardarOferta:output_type -> AckResponse
	8,  // 12: DynamoDB.LeerHistorico:output_type -> HistoricoResponse
	10, // 13: DynamoDB.Sincronizar:output_type -> SincronizarResponse
	4,  // 14: Consumidor.RegistrarConsumidor:output_type -> RegistroConsumidorResponse
	6,  // 15: Consumidor.SolicitarHistorico:output_type -> HistoricoConsumidorResponse
	2,  // 16: NotificacionesConsumidor.RecibirOferta:output_type -> AckResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_ofertas_proto_init() }
func file_proto_ofertas_proto_init() {
	if File_proto_ofertas_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ofertas_proto_rawDesc), len(file_proto_ofertas_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_proto_ofertas_proto_goTypes,
		DependencyIndexes: file_proto_ofertas_proto_depIdxs,
		MessageInfos:      file_proto_ofertas_proto_msgTypes,
	}.Build()
	File_proto_ofertas_proto = out.File
	file_proto_ofertas_proto_goTypes = nil
	file_proto_ofertas_proto_depIdxs = nil
}
